ioctls: videodev2: check if defines are obsolete
In kernel headers 3.11 the VIDIOC_DBG_G_CHIP_IDENT define is
considered obsolete, therefore removed, generating the following
compiling error:

ioctls/videodev2.c:72:15: error: ‘VIDIOC_DBG_G_CHIP_IDENT’ undeclared here (not in a function)
  IOCTL(VIDIOC_DBG_G_CHIP_IDENT),
               ^

Check the definition of it before using it

Signed-off-by: Andi Shyti <andi@etezian.org>