Remove leftover udp.h include.
Fix build error.

  CC	fds/drm.o
fds/drm.c:26:10: fatal error: udp.h: No such file or directory
   26 | #include "udp.h"
      |          ^~~~~~~

Fixes: c927ff98280b ("remove all the udp logging")
Signed-off-by: Vinson Lee <vlee@freedesktop.org>