net: include <linux/if.h> instead of <net/if.h>
Commit 4ada80dd202675 includes net/if.h and linux/netfilter_ipv4/ip_tables.h
net/* and linux/* should not be mixed.
Debian Jessie x86_64:
  CC    net/proto-ipv4.o
  In file included from net/proto-ipv4.c:11:0:
  /usr/include/linux/if.h:71:2: error: redeclaration of enumerator 'IFF_UP'
    IFF_UP    = 1<<0,  /* sysfs */
  /usr/include/net/if.h:44:5: note: previous definition of 'IFF_UP' was here
    IFF_UP = 0x1,  /* Interface is up.  */
  [...]

Signed-off-by: Adrien Schildknecht <adrien+dev@schischi.me>