configure: fix memfd_create check
from man page, it requires _GNU_SOURCE, and it requires two parameters.
it would hit copmile broken if not fixed on fedora 40.

Before the fix:
[trinity]$ make
  CC    debug.o
  CC    trinity.o
  CC    fds/memfd.o
fds/memfd.c:22:12: error: static declaration of ‘memfd_create’ follows non-static declaration
   22 | static int memfd_create(__unused__ const char *uname, __unused__ unsigned int flag)
      |            ^~~~~~~~~~~~
In file included from /usr/include/bits/mman-linux.h:116,
                 from /usr/include/bits/mman.h:38,
                 from /usr/include/sys/mman.h:41,
                 from fds/memfd.c:8:
/usr/include/bits/mman-shared.h:55:5: note: previous declaration of ‘memfd_create’ with type ‘int(const char *, unsigned int)’
   55 | int memfd_create (const char *__name, unsigned int __flags) __THROW;
      |     ^~~~~~~~~~~~
make: *** [Makefile:113: fds/memfd.o] Error 1

After the fix:
[trinity]$ cat /etc/redhat-release
Fedora release 40 (Forty)
[trinity]$ ./configure | grep memfd_create
[*] Checking if glibc provides memfd_create.. [YES]

[trinity]$ make -j8 | grep memfd_create
  CC    syscalls/memfd_create.o

Signed-off-by: Chunyu Hu <chuhu@redhat.com>