Fix build with kernel 3.4 headers.
PR_SET_CHILD_SUBREAPER was added in kernel 3.4 but PR_SET_NO_NEW_PRIVS,
PR_GET_NO_NEW_PRIVS, and PR_GET_TID_ADDRESS were added in kernel 3.5.

  CC	syscalls/prctl.o
syscalls/prctl.c:33: error: ‘PR_SET_NO_NEW_PRIVS’ undeclared here (not in a function)
syscalls/prctl.c:34: error: ‘PR_GET_NO_NEW_PRIVS’ undeclared here (not in a function)
syscalls/prctl.c:34: error: ‘PR_GET_TID_ADDRESS’ undeclared here (not in a function)

Signed-off-by: Vinson Lee <vlee@twitter.com>