Makefile: fix build with older glibc
man 2 clock_gettime says:
Link with -lrt (only for glibc versions before 2.17).

If we do not do that, we get:
post-mortem.c:61: undefined reference to `clock_gettime'
syscall.o: In function `__do_syscall':
syscall.c:121: undefined reference to `clock_gettime'
watchdog.o: In function `is_child_making_progress':
watchdog.c:317: undefined reference to `clock_gettime'

So introduce (standard) LDLIBS into Makefile and add -lrt there.

Signed-off-by: Jiri Slaby <jslaby@suse.cz>