Check if VIDIOC_RESERVED is defined.
VIDIOC_RESERVED was removed in Linux 4.19.

commit ea8532daee31bc72abfbc9ca7a43cbec0f6c05af
Author: Mauro Carvalho Chehab <mchehab+samsung@kernel.org>
Date:   Wed May 30 11:07:05 2018 -0400

    media: videodev2: get rid of VIDIOC_RESERVED

    While this ioctl is there at least since Kernel 2.6.12-rc2, it
    was never used by any upstream driver.

    Get rid of it.

    Signed-off-by: Mauro Carvalho Chehab <mchehab+samsung@kernel.org>

This patch fixes this build error.

  CC	ioctls/videodev2.o
In file included from ioctls/videodev2.c:4:
ioctls/videodev2.c:8:8: error: ‘VIDIOC_RESERVED’ undeclared here (not in a function); did you mean ‘VIDIOC_G_STD’?
  IOCTL(VIDIOC_RESERVED),
        ^~~~~~~~~~~~~~~
include/ioctls.h:53:15: note: in definition of macro ‘IOCTL’
  { .request = _request, .name = #_request, }
               ^~~~~~~~

Signed-off-by: Vinson Lee <vlee@freedesktop.org>