mlock: move MLOCK_ONFAULT to compat.h
It got defined in our headers, so it causes build failures:
syscalls/mlock.c:30:0: error: "MLOCK_ONFAULT" redefined [-Werror]
 #define MLOCK_ONFAULT   0x01

In file included from /usr/include/bits/mman-linux.h:115:0,
                 from /usr/include/bits/mman.h:45,
                 from /usr/include/sys/mman.h:41,
                 from include/utils.h:4,
                 from include/syscall.h:7,
                 from include/child.h:7,
                 from include/shm.h:4,
                 from syscalls/mlock.c:6:
/usr/include/bits/mman-shared.h:33:0: note: this is the location of the previous definition
 #  define MLOCK_ONFAULT 1U

So move it out of our way.

Signed-off-by: Jiri Slaby <jslaby@suse.cz>