fix builds for older kernels (#59)
* compat: in6: add some IPV6_ constants

Add
* IPV6_FLOWINFO
* IPV6_FLOWLABEL_MGR
* IPV6_FLOWINFO_SEND
fallbacks to include/kernel/in6.h -- SL 16.0 does not define those in
<netinet/in.h>, so we need to.

net/proto/ipv6.c:118:19: error: ‘IPV6_FLOWINFO’ undeclared here (not in a function); did you mean ‘IPV6_2292FLOWINFO’?

* vm_sockets: include sys/socket.h

This was fixed upstream in 22bbc1dcd0d6 ("vsock/uapi: fix
linux/vm_sockets.h userspace compilation errors"). This is not present
on older kernels like on SL-16.0.

---------

Co-authored-by: Jiri Slaby <jslaby@suse.cz>