Add #ifdefs around missing exynos ioctls on earlier kernels.
This patch fixes these build errors with Linux 3.4 and earlier.

  CC	ioctls/drm.o
ioctls/drm.c:179: error: ‘DRM_IOCTL_EXYNOS_GEM_GET’ undeclared here (not in a function)
ioctls/drm.c:181: error: ‘DRM_IOCTL_EXYNOS_G2D_GET_VER’ undeclared here (not in a function)
ioctls/drm.c:182: error: ‘DRM_IOCTL_EXYNOS_G2D_SET_CMDLIST’ undeclared here (not in a function)
ioctls/drm.c:183: error: ‘DRM_IOCTL_EXYNOS_G2D_EXEC’ undeclared here (not in a function)
make: *** [ioctls/drm.o] Error 1

Signed-off-by: Vinson Lee <vlee@twitter.com>