Add missing EPOLLWAKEUP define to compat.h for older distros
  CC    syscalls/epoll_ctl.o
syscalls/epoll_ctl.c:14:2: error: ‘EPOLLWAKEUP’ undeclared here (not in a function)

Signed-off-by: Brian Haley <brian.haley@hp.com>