ioctls/drm: Fix build errors due to undefined symbols.
This patch fixes these build errors on Fedora 22
3.18.0-0.rc0.git9.4.fc22.x86_64.

  CC	ioctls/drm.o
In file included from ioctls/drm.c:20:0:
ioctls/drm.c:274:8: error: ‘DRM_IOCTL_EXYNOS_GEM_MAP_OFFSET’ undeclared here (not in a function)
  IOCTL(DRM_IOCTL_EXYNOS_GEM_MAP_OFFSET),
        ^
include/ioctls.h:53:15: note: in definition of macro ‘IOCTL’
  { .request = _request, .name = #_request, }
               ^
ioctls/drm.c:275:8: error: ‘DRM_IOCTL_EXYNOS_GEM_MMAP’ undeclared here (not in a function)
  IOCTL(DRM_IOCTL_EXYNOS_GEM_MMAP),
        ^
include/ioctls.h:53:15: note: in definition of macro ‘IOCTL’
  { .request = _request, .name = #_request, }
               ^

Signed-off-by: Vinson Lee <vlee@twitter.com>