ioctl/vt: fix compilation on ppc (RHEL7, 3.8)
on x86_64:
asm/termios.h includes
  asm-generic/termios.h
    asm/termbits.h
      asm-generic/termbits.h
        defines struct termios and termios2

on ppc64:
asm/termios.h includes
  asm/termbits.h
    defines struct termios

Including asm/termbits.h creates a conflict on ppc, because struct
termios is defined in /usr/include/bits/termios.h and also in
/usr/include/asm/termbits.h.

  # make
    CC	ioctls/vt.o
  In file included from ioctls/vt.c:4:0:
  /usr/include/asm/termbits.h:22:8: error: redefinition of ‘struct
  termios’
  In file included from /usr/include/termios.h:40:0,
                   from /usr/include/bits/ioctl-types.h:5,
                   from /usr/include/sys/ioctl.h:29,
                   from ioctls/vt.c:2:
  /usr/include/bits/termios.h:33:8: note: originally defined here
  ioctls/vt.c:120:2: error: ‘TCGETS2’ undeclared here (not in a function)
  ioctls/vt.c:121:2: error: ‘TCSETS2’ undeclared here (not in a function)
  ioctls/vt.c:122:2: error: ‘TCSETSW2’ undeclared here (not in a function)
  ioctls/vt.c:123:2: error: ‘TCSETSF2’ undeclared here (not in a function)
  make: *** [ioctls/vt.o] Error 1

Also asm-generic/ioctls.h which defines TCGETS2 and others is not
included by any other header file on ppc.

This patch adds check if struct termios2 is provided by glibc headers,
if not it is defined in place instead of including asm/termbits.h.

Signed-off-by: Jan Stancek <jstancek@redhat.com>