ptrace: fix build on archs without PTRACE_GETREGS et al. (#56)
Defining those to 0 makes the compiler to complain with an error:
 syscalls/ptrace.c:115:9: error: duplicate case value
   115 |         case PTRACE_GETFPREGS:
       |         ^~~~
 syscalls/ptrace.c:114:9: note: previously used here
   114 |         case PTRACE_GETREGS:
       |         ^~~~

Define them to the ABI numbers instead of 0.