Remove unused variable in fds/drm.c.
Fix build error with GCC 5.2.1.

  CC	fds/drm.o
fds/drm.c: In function ‘open_drm_fds’:
fds/drm.c:70:15: error: unused variable ‘i’ [-Werror=unused-variable]
  unsigned int i;
               ^

Signed-off-by: Vinson Lee <vlee@freedesktop.org>