fds/drm.c: Increase buffer size.
Fix GCC format-truncation error.

  CC	fds/drm.o
fds/drm.c: In function ‘open_drm_fds’:
fds/drm.c:106:40: error: ‘%s’ directive output may be truncated writing up to 255 bytes into a region of size 119 [-Werror=format-truncation=]
   snprintf(buf, sizeof(buf), "/dev/dri/%s", entry->d_name);
                                        ^~
In file included from /usr/include/stdio.h:939:0,
                 from include/list.h:3,
                 from include/fd.h:3,
                 from fds/drm.c:4:
/usr/include/bits/stdio2.h:64:10: note: ‘__builtin___snprintf_chk’ output between 10 and 265 bytes into a destination of size 128
   return __builtin___snprintf_chk (__s, __n, __USE_FORTIFY_LEVEL - 1,
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        __bos (__s), __fmt, __va_arg_pack ());
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Signed-off-by: Vinson Lee <vlee@freedesktop.org>

[ changed to 256+10 -- davej ]