drop decnet
Drop decnet as it has been removed since kernel 6.1 and
https://github.com/torvalds/linux/commit/1202cdd665315c525b5237e96e0bedc76d7e754f
resulting in the following build failure:

net/proto-decnet.c:5:10: fatal error: linux/dn.h: No such file or directory
    5 | #include <linux/dn.h>
      |          ^~~~~~~~~~~~

Fixes:
 - http://autobuild.buildroot.org/results/47e0a5e0b6fcf33ab4f9848d5d8c2be9e5283950

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>