mips: fix prctl's
It looks like a typo in the syscalls/prctl.c file. It's lacking the PR_
preffix, and due to that is causing build failures like this one:

  CC	syscalls/prctl.o
syscalls/prctl.c:37:2: error: 'GET_FP_MODE' undeclared here (not in a
function)
  GET_FP_MODE, SET_FP_MODE,
  ^
syscalls/prctl.c:37:15: error: 'SET_FP_MODE' undeclared here (not
in a function)
  GET_FP_MODE, SET_FP_MODE,
               ^

Signed-off-by: Vicente Olivert Riera <Vincent.Riera@imgtec.com>