socket: Fix missing-field-initializers build error.
This patch fixes this build error.

  CC	syscalls/socket.o
syscalls/socket.c:48:2: error: missing initializer for field ‘func’ of ‘const struct socket_ptr’ [-Werror=missing-field-initializers]
  [AF_ECONET] = {  }, // DEAD
  ^
syscalls/socket.c:22:9: note: ‘func’ declared here
  void (*func)(struct socket_triplet *st);
         ^

Signed-off-by: Vinson Lee <vlee@twitter.com>