ioctls/atm: use ATM_ADDPARTY/ATM_DROPPARTY only if defined
They were dropped in 7.2 by 8f9616500c59 ("atm: remove orphaned uAPI for
deleted drivers, protocols and SVCs"). So do not use them when
undefined.

To fix:
  ioctls/atm.c:292:15: error: ‘ATM_ADDPARTY’ undeclared here (not in a function)