timerfd_create: Include time.h instead of sys/timerfd.h.
This patch fixes these build errors with glibc before 2.8.

syscalls/timerfd_create.c:4:25: error: sys/timerfd.h: No such file or directory
syscalls/timerfd_create.c:15: error: ‘CLOCK_REALTIME’ undeclared here (not in a function)
syscalls/timerfd_create.c:15: error: ‘CLOCK_MONOTONIC’ undeclared here (not in a function)

Signed-off-by: Vinson Lee <vlee@twitter.com>