proto-phonet: Include compat.h.
Fix build error when missing PF_PHONET with glibc < 2.10.

  CC	net/proto-phonet.o
net/proto-phonet.c: In function ‘phonet_gen_sockaddr’:
net/proto-phonet.c:17:19: error: ‘PF_PHONET’ undeclared (first use in this function)
  pn->spn_family = PF_PHONET;
                   ^

Signed-off-by: Vinson Lee <vlee@twitter.com>