vt.c: add missing include to fix building with uClibc
"#include <linux/serial.h>" is needed in order to build trinity
successfully with uClibc. Otherwise it would fail displaying an error
message like this one:

ioctls/vt.c:152:8: error: invalid application of 'sizeof' to incomplete
type 'struct serial_rs485'
  IOCTL(TIOCGRS485),

ioctls/vt.c:155:8: error: invalid application of 'sizeof' to incomplete
type 'struct serial_rs485'
  IOCTL(TIOCSRS485),

Signed-off-by: Vicente Olivert Riera <Vincent.Riera@imgtec.com>