maps: Rename MAP_{GLOBAL, LOCAL} to TRINITY_MAP_{GLOBAL, LOCAL}
The MAP_LOCAL flag is actually a valid flag and some architectures
make use of it according to the mmap manpage. More specifically,
MIPS and Xtensa define the MAP_LOCAL flag in their userpsace mman.h
header leading to build problems like this:

In file included from syscalls/mprotect.c:6:0:
include/maps.h:8:0: error: "MAP_LOCAL" redefined [-Werror]
 #define MAP_LOCAL 2
 ^
In file included from syscalls/mprotect.c:4:0:
/toolchain/mips-linux-gnu/libc/usr/include/asm/mman.h:37:0:
note: this is the location of the previous definition
 #define MAP_LOCAL 0x080  /* Copy on fork/sproc */
 ^

Therefore, we rename the definitions in trinity to avoid conflicts
with the linux headers.

Signed-off-by: Markos Chandras <markos.chandras@imgtec.com>