net/bpf.c: Remove AUDIT_ARCH_H8300.
AUDIT_ARCH_H8300 was removed from include/uapi/linux/audit.h in Linux
3.13 commit 6f6f467eaaa0ac4fb77714d0172d65c781dabb8c.

commit 6f6f467eaaa0ac4fb77714d0172d65c781dabb8c
Author: Guenter Roeck <linux@roeck-us.net>
Date:   Fri Aug 30 06:12:40 2013 -0700

    Drop remaining references to H8/300 architecture

    With the architecture gone, any references to it are no longer needed.

    Cc: Yoshinori Sato <ysato@users.sourceforge.jp>
    Acked-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
    Signed-off-by: Guenter Roeck <linux@roeck-us.net>

This patch fixes this build error.

  CC	net/bpf.o
net/bpf.c:135:18: error: ‘AUDIT_ARCH_H8300’ undeclared here (not in a function)
  AUDIT_ARCH_FRV, AUDIT_ARCH_H8300, AUDIT_ARCH_I386, AUDIT_ARCH_IA64,
                  ^

Signed-off-by: Vinson Lee <vlee@twitter.com>
Acked-by: Daniel Borkmann <dborkman@redhat.com>